# Generated by Django 3.1.6 on 2021-02-03 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name='Put the description'),
        ),
    ]
