# Generated by Django 3.1.6 on 2021-03-04 06:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210219_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_snippet',
            field=models.TextField(default='Tutorial'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor.fields.RichTextField(max_length=10000000, verbose_name='Put the description'),
        ),
    ]
